ci: move composite action to .github/actions
Failed to load /home/runner/work/distributed-verification/distributed-verification/./.github/verify-rust-std/init/action.yml
kani-list / ubuntu-latest
GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. /home/runner/work/distributed-verification/distributed-verification/./.github/verify-rust-std/init/action.yml (Line: 6, Col: 7): Required property is missing: shell,/home/runner/work/distributed-verification/distributed-verification/./.github/verify-rust-std/init/action.yml (Line: 9, Col: 7): Required property is missing: shell
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)