ci: fix missing shell field
Error: /home/runner/work/distributed-verification/distributed-verification/./.github/actions/init/action.yml (Line: 6, Col: 7): Required property is missing: shell
Error: /home/runner/work/distributed-verification/distributed-verification/./.github/actions/init/action.yml (Line: 9, Col: 7): Required property is missing: shell
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. /home/runner/work/distributed-verification/distributed-verification/./.github/actions/init/action.yml (Line: 6, Col: 7): Required property is missing: shell,/home/runner/work/distributed-verification/distributed-verification/./.github/actions/init/action.yml (Line: 9, Col: 7): Required property is missing: shell