ci(verify): patch log_parser due to uninitialized autoharness_info
UnboundLocalError: cannot access local variable 'autoharness_info' where it is not associated with a value