ci: don't checkout to COMMIT_KANI; weird bug in CI
+ COMMIT_VERIFY_RUST_STD=571c8ac
+ COMMIT_KANI=d6853436382d876e574fb8a3fdef5b798a6e7d0d
+ pushd kani
+ git pull origin main --rebase
~/work/distributed-verification/distributed-verification/kani ~/work/distributed-verification/distributed-verification
From https://github.com/model-checking/kani
 * branch            main       -> FETCH_HEAD
Auto-merging rust-toolchain.toml
CONFLICT (add/add): Merge conflict in rust-toolchain.toml
Rebasing (1/1)
error: could not apply 8b586cd... Add setup scripts for Ubuntu 20.04 (#4082)
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
Could not apply 8b586cd... Add setup scripts for Ubuntu 20.04 (#4082)